- generator: rvoxgen.pymutable:PythonMutableGenerator
  spec_base: rvoxgen/
  dest_base: rv/

#- generator: rvoxgen.pyimmutable:PythonImmutableGenerator
#
#- generator: rvoxgen.jsmutable:JavascriptMutableGenerator
#
#- generator: rvoxgen.jsimmutable:JavascriptImmutableGenerator
#
#- generator: rvoxgen.piximutable:PixilangMutableGenerator
